### ISSUE TITLE
Installation error: nimporter.NimCompileException:  cannot open file: cello

### ISSUE THREAD

**Issue by ChongLC** [Benjamin-Lee/vdsearch#12]
Dear developer, 

I have installed vdsearch. However, I faced this issue while running $ "vdsearch --help". 

Error: 
```
Traceback (most recent call last):
  File "/home/chong/miniconda3/bin/vdsearch", line 33, in <module>
    sys.exit(load_entry_point('vdsearch==0.0.1', 'console_scripts', 'vdsearch')())
  File "/home/chong/miniconda3/bin/vdsearch", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/chong/miniconda3/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/home/chong/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/chong/miniconda3/lib/python3.8/site-packages/vdsearch-0.0.1-py3.8-linux-x86_64.egg/vdsearch/main.py", line 8, in <module>
    from . import commands
  File "/home/chong/miniconda3/lib/python3.8/site-packages/vdsearch-0.0.1-py3.8-linux-x86_64.egg/vdsearch/commands/__init__.py", line 1, in <module>
    from .canonicalize import canonicalize
  File "/home/chong/miniconda3/lib/python3.8/site-packages/vdsearch-0.0.1-py3.8-linux-x86_64.egg/vdsearch/commands/canonicalize.py", line 9, in <module>
    from vdsearch.nim import canonicalize as rotcanon
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 914, in _find_spec
  File "/home/chong/miniconda3/lib/python3.8/site-packages/nimporter.py", line 1269, in find_spec
    return Nimporter.import_nim_code(fullname, path, library=False)
  File "/home/chong/miniconda3/lib/python3.8/site-packages/nimporter.py", line 944, in import_nim_code
    NimCompiler.compile_nim_code(
  File "/home/chong/miniconda3/lib/python3.8/site-packages/nimporter.py", line 705, in compile_nim_code
    cls.check_compile_errors(errors, library, nim_args, output, tmp_cwd, warnings)
  File "/home/chong/miniconda3/lib/python3.8/site-packages/nimporter.py", line 492, in check_compile_errors
    raise NimCompileException(errors[0])
nimporter.NimCompileException:  cannot open file: cello
 |  import bioseq
 -> import cello
 |  import strutils
 |

At /home/chong/chris/fungi_RNA/revised_genome_plot/mmseqs_clustering/vdsearch/vdsearch/nim/canonicalize.nim 5:8
```

Any suggestion to solve this issue? 

Best regards, 
Chong

**Comment by mherold1** [comment]
Hi, not sure if this is still relevant, but I had the same and upgrading pip and cython fixed this for me
